from transformers import AutoTokenizer, AutoModelForCausalLM
from huggingface_hub import login
import os
from dotenv import load_dotenv
import torch

load_dotenv()

hf_token = os.getenv("hf_token")
if hf_token:
    login(hf_token)

LOAD_DIR = os.getenv("model_dir")
if not LOAD_DIR:
    raise ValueError("model_dir not set in environment variables.")

SEQ_LENGTH = 3000
TEMP = 0.9
device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained(LOAD_DIR)
model = AutoModelForCausalLM.from_pretrained(LOAD_DIR)

model.to(device)
model.eval()

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

def format_prompt(prompt):
    messages = [
        {
            "role": "system",
            "content": f"""You are a Computer Science teacher. Generate hard multiple choice questions from the context given.
Each MCQ must follow this format:
Question: ...
A. ...
B. ...
C. ...
D. ...
Answer: X
Ensure there is no repetition. Questions must be meaningful and test deep understanding.""",
        },
        {"role": "user", "content": prompt},
    ]
    return tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )

def generate_mcqs_from_text(user_prompt):
    from transformers import TextIteratorStreamer
    import threading

    prompt = format_prompt(user_prompt)
    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    # For Streamed Output
    streamer = TextIteratorStreamer(
        tokenizer,
        skip_prompt=True,
        skip_special_tokens=True,
    )

    generation_kwargs = dict(
        **inputs,
        max_new_tokens=SEQ_LENGTH,
        do_sample=True,
        temperature=TEMP,
        streamer=streamer,
    )

    def generate():
        # Doesnot calculates Gradients, i.e. Optimized way of inferencing
        with torch.inference_mode():
            model.generate(**generation_kwargs)
    
    # Threading for Streamed Output, Main thread pulls the Tokens generated by Model.generate thread
    thread = threading.Thread(target=generate)
    thread.start()

    for token in streamer:
        yield token

    thread.join()
